// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcJ-6VKjn01jxEfzNeNhN6TTt12m62uE',
    appId: '1:541618656719:web:ec31cdfd03917d90abeeba',
    messagingSenderId: '541618656719',
    projectId: 'financetracker-c09f7',
    authDomain: 'financetracker-c09f7.firebaseapp.com',
    storageBucket: 'financetracker-c09f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9mVIl91gdOOKvQsoAXN1zFId86veqHI',
    appId: '1:541618656719:android:09e38f6f0374cd75abeeba',
    messagingSenderId: '541618656719',
    projectId: 'financetracker-c09f7',
    storageBucket: 'financetracker-c09f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM59QBYa5CwS09fZfHSDKwILwlN_mIgu8',
    appId: '1:541618656719:ios:1c2303de74e2f4ababeeba',
    messagingSenderId: '541618656719',
    projectId: 'financetracker-c09f7',
    storageBucket: 'financetracker-c09f7.firebasestorage.app',
    iosBundleId: 'com.example.abschlussProjekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM59QBYa5CwS09fZfHSDKwILwlN_mIgu8',
    appId: '1:541618656719:ios:1c2303de74e2f4ababeeba',
    messagingSenderId: '541618656719',
    projectId: 'financetracker-c09f7',
    storageBucket: 'financetracker-c09f7.firebasestorage.app',
    iosBundleId: 'com.example.abschlussProjekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUcJ-6VKjn01jxEfzNeNhN6TTt12m62uE',
    appId: '1:541618656719:web:23a9cc2eb38ac548abeeba',
    messagingSenderId: '541618656719',
    projectId: 'financetracker-c09f7',
    authDomain: 'financetracker-c09f7.firebaseapp.com',
    storageBucket: 'financetracker-c09f7.firebasestorage.app',
  );
}
